// Enum types based on Prisma schema

export enum UserType {
  ADMIN = 'ADMIN',
  SUPERADMIN = 'SUPERADMIN',
  GUEST = 'GUEST',
  OWNER = 'OWNER',
}

export enum CollegeType {
  TECHNICAL = 'TECHNICAL',
  MEDICAL = 'MEDICAL',
  ARTS = 'ARTS',
  OTHER = 'OTHER',
}

export enum SectionType {
  HEADER = 'HEADER',
  HERO = 'HERO',
  ABOUT = 'ABOUT',
  ACTIONS = 'ACTIONS',
  NUMBERS = 'NUMBERS',
  COLLEGES_SECTION = 'COLLEGES_SECTION',
  OUR_MISSION = 'OUR_MISSION',
  STUDENT_UNION = 'STUDENT_UNION',
  EGYPT_STUDENT_GROUP = 'EGYPT_STUDENT_GROUP',
  COLLEGES = 'COLLEGES',
  CUSTOM = 'CUSTOM',
}

export enum PageType {
  HOME = 'HOME',
  ABOUT = 'ABOUT',
  CONTACT = 'CONTACT',
  PRIVACY = 'PRIVACY',
  TERMS = 'TERMS',
  BLOGS = 'BLOGS',
  STUDENT_ACTIVITIES = 'STUDENT_ACTIVITIES',
  STUDENT_UNIONS = 'STUDENT_UNIONS',
  CUSTOM = 'CUSTOM',
}

export enum Action {
  VIEW = 'VIEW',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
  CREATE = 'CREATE',
}
