// Enum types based on Prisma schema

export enum UserType {
  ADMIN = 'ADMIN',
  SUPERADMIN = 'SUPERADMIN',
  GUEST = 'GUEST',
  OWNER = 'OWNER',
}

export enum CollegeType {
  TECHNICAL = 'TECHNICAL',
  MEDICAL = 'MEDICAL',
  ARTS = 'ARTS',
  OTHER = 'OTHER',
}

export enum SectionType {
  HEADER = 'HEADER',
  HERO = 'HERO',
  ABOUT = 'ABOUT',
  ACTIONS = 'ACTIONS',
  OUR_MISSION = 'OUR_MISSION',
  NUMBERS = 'NUMBERS',
  STUDENT_UNION = 'STUDENT_UNION',
  COLLEGES_SECTION = 'COLLEGES_SECTION',
  PROGRAMS_SECTION = 'PROGRAMS_SECTION',
  EGYPT_STUDENT_GROUP = 'EGYPT_STUDENT_GROUP',
  PRESIDENT = 'PRESIDENT',
  BLOGS = 'BLOGS',
  CONTACT_US = 'CONTACT_US',
  CUSTOM = 'CUSTOM',
  STUDENT_ACTIVITIES = 'STUDENT_ACTIVITIES',
}

export enum PageSectionType {
  HERO1 = 'HERO1',
  HERO2 = 'HERO2',
  ABOUT1 = 'ABOUT1',
  ABOUT2 = 'ABOUT2',
  CONTACT = 'CONTACT',
  BLOGS = 'BLOGS',
  PRESIDENT = 'PRESIDENT',
  STUDENT_ACTIVITIES = 'STUDENT_ACTIVITIES',
  STUDENT_UNIONS = 'STUDENT_UNIONS',
  PRESIDENT_MESSAGE = 'PRESIDENT_MESSAGE',
  FOR_EGYPT_GROUP = 'FOR_EGYPT_GROUP',
  OUR_HISTORY = 'OUR_HISTORY',
  CUSTOM = 'CUSTOM',
}

export enum Action {
  VIEW = 'VIEW',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
  CREATE = 'CREATE',
}
